services:
  db:
    image: postgres
    container_name: monedas_api
    environment:
      POSTGRES_USER: Carlos
      POSTGRES_PASSWORD: chinchinPrueba
      POSTGRES_DB: monedas_api
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
